# Generated by Django 3.1.3 on 2020-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
    ]
