# Generated by Django 3.1.3 on 2020-11-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
