# Generated by Django 3.1.3 on 2020-11-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastaApp', '0003_auto_20201113_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.RemoveField(
            model_name='fotos',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
